#!/bin/sh

# Set defaults
SLACK_WEBHOOK=${INPUT_SLACK_WEBHOOK}
STATUS=${INPUT_STATUS}
AUTHOR_NAME=${INPUT_AUTHOR_NAME:-"GitHub Action"}
AUTHOR_LINK=${INPUT_AUTHOR_LINK:-""}
AUTHOR_ICON=${INPUT_AUTHOR_ICON:-""}
TITLE=${INPUT_TITLE:-"Build Notification"}
TITLE_LINK=${INPUT_TITLE_LINK:-""}
MESSAGE=${INPUT_MESSAGE:-"Notification from GitHub Action"}
COLOR=${INPUT_COLOR:-"#36a64f"}
SLACK_TOKEN=${INPUT_SLACK_TOKEN}
CHANNEL_ID=${INPUT_CHANNEL_ID}
SLACK_THREAD_TS=${INPUT_SLACK_THREAD_TS}

# Export the variables
export SLACK_WEBHOOK
export STATUS
export AUTHOR_NAME
export AUTHOR_LINK
export AUTHOR_ICON
export TITLE
export TITLE_LINK
export MESSAGE
export COLOR
export SLACK_TOKEN
export CHANNEL_ID
export SLACK_THREAD_TS

# Run
python3 run.py